version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: deno_api_postgres
    environment:
      POSTGRES_USER: deno_user
      POSTGRES_PASSWORD: deno_password
      POSTGRES_DB: deno_api_db
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U deno_user -d deno_api_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:latest
    container_name: deno_api_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: deno_user
      MONGO_INITDB_ROOT_PASSWORD: deno_password
      MONGO_INITDB_DATABASE: deno_api_db
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://deno_user:deno_password@localhost:27017/deno_api_db --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

# Adicione este serviço ao seu docker-compose.yml existente
  deno:
    image: denoland/deno:latest
    container_name: deno_api_app
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - deno_cache:/deno-dir
    working_dir: /app
    command: deno task dev
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://deno_user:deno_password@postgres:5432/deno_api_db
      - MONGODB_URI=mongodb://deno_user:deno_password@mongodb:27017/deno_api_db
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - FRONTEND_REDIRECT_URI=${FRONTEND_REDIRECT_URI}
volumes:
  postgres_data:
  mongodb_data:
  deno_cache: