version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: deno_api_postgres
    environment:
      POSTGRES_USER: deno_user
      POSTGRES_PASSWORD: deno_password
      POSTGRES_DB: deno_api_db
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U deno_user -d deno_api_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: